### ISSUE TITLE
Claim a ticket with email

### ISSUE THREAD

**Issue by soub4i** [DevC-Casa/ticket.blablaconf.com#2]
Hello 

I suggest claiming a ticket with an email only and if the visitor wants to customize it we can use Github as the second step so we can give the chance for people that are not on Github to have a ticket.

Motivation: Nextjs tickting system https://nextjs.org/conf

**Comment by yjose** [comment]
@AbderrahimSoubaiElidrissi  i think we did the same thing but this repo is only to generate the ticket with GitHub data. 
Go to the home page [https://blablaconf.webflow.io/](https://blablaconf.webflow.io/)  the complete process,  I know it's not optimal  but this is what we can do for now unless you have some new thoughts

**Comment by soub4i** [comment]
Thanks for your fast answer @yjose my bad I didn't know about the webflow process looks smooth
